In [22]:


from Translator.dataset import get_translation_dataset
from torch.utils.data import Dataset, DataLoader

In [35]:
class TestDataset(Dataset):
    def __init__(self, dataset):
        super().__init__()
        self.dataset = dataset
    def __len__(self):
        return len(self.dataset)
    def __getitem__(self, idx):
        return {"idx": idx, "content": self.dataset[idx]}

In [25]:
ds_raw = get_translation_dataset('de', 'en', '16')

In [36]:
ds = TestDataset(ds_raw["train"])

In [39]:
dl = DataLoader(ds, batch_size=2, shuffle=True)

In [40]:
for batch in dl:
    print(batch)
    break

{'idx': tensor([ 974229, 3576879]), 'content': {'translation': {'de': ['Damit muss Schluss sein.', 'Möglich, in etwas sind sie gültig recht.'], 'en': ['That is enough.', 'I had taken care of a whole column for the whole year in that paper, and it had been challenging and inspiring. Once a week my article went out about television and movie theater art in front of the readers.']}}}


In [49]:
import torch
batch_size = 16
seq_len = 256
vocab_size = 10006
A = torch.randint(0, 100, (batch_size,seq_len,vocab_size))
B = torch.randint(0, 100, (batch_size,seq_len))

In [52]:
print(B.view(-1).shape)

torch.Size([4096])


In [54]:
torch.empty(1,1).fill_(1).shape

torch.Size([1, 1])

In [56]:
torch.Tensor([[1]]).shape

torch.Size([1, 1])

In [84]:
mask = torch.tril(torch.ones((1, 10, 10))).type(torch.bool)

In [85]:
mask

tensor([[[ True, False, False, False, False, False, False, False, False, False],
         [ True,  True, False, False, False, False, False, False, False, False],
         [ True,  True,  True, False, False, False, False, False, False, False],
         [ True,  True,  True,  True, False, False, False, False, False, False],
         [ True,  True,  True,  True,  True, False, False, False, False, False],
         [ True,  True,  True,  True,  True,  True, False, False, False, False],
         [ True,  True,  True,  True,  True,  True,  True, False, False, False],
         [ True,  True,  True,  True,  True,  True,  True,  True, False, False],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True, False],
         [ True,  True,  True,  True,  True,  True,  True,  True,  True,  True]]])

In [86]:
A = torch.randint(0,3,(10,))
print(A)
(A==2).unsqueeze(0)

tensor([2, 1, 0, 2, 1, 2, 2, 0, 2, 1])


tensor([[ True, False, False,  True, False,  True,  True, False,  True, False]])

In [94]:
new_mask = mask | (A==2).unsqueeze(0)

In [95]:
B = torch.randint(0,3,(1,10,10)).masked_fill_(new_mask,-1)

In [96]:
B

tensor([[[-1,  1,  1, -1,  0, -1, -1,  1, -1,  1],
         [-1, -1,  1, -1,  2, -1, -1,  0, -1,  2],
         [-1, -1, -1, -1,  1, -1, -1,  2, -1,  2],
         [-1, -1, -1, -1,  0, -1, -1,  1, -1,  0],
         [-1, -1, -1, -1, -1, -1, -1,  2, -1,  2],
         [-1, -1, -1, -1, -1, -1, -1,  1, -1,  0],
         [-1, -1, -1, -1, -1, -1, -1,  2, -1,  0],
         [-1, -1, -1, -1, -1, -1, -1, -1, -1,  1],
         [-1, -1, -1, -1, -1, -1, -1, -1, -1,  2],
         [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]]])

In [ ]:
# berechne nur, wenn i < j und wenn bei i kein padding

In [ ]:
"""
Wenn mask == 0 dann setze attention scores auf -inf
maske bei ihm: mask = torch.triu(torch.ones((1, size, size)), diagonal=1).type(torch.int) == 0
"""

In [102]:
sequence = torch.tensor([1, 4, 2, 3, 5, 6, -1, -1, -1, -1])

In [105]:
mask1 = torch.triu(torch.ones((1, 10, 10)), diagonal=1).type(torch.int) == 0
mask2 = torch.tril(torch.ones((1, 10, 10))).type(torch.bool)

final_mask = (sequence != -1) & mask2
print(final_mask)

tensor([[[ True, False, False, False, False, False, False, False, False, False],
         [ True,  True, False, False, False, False, False, False, False, False],
         [ True,  True,  True, False, False, False, False, False, False, False],
         [ True,  True,  True,  True, False, False, False, False, False, False],
         [ True,  True,  True,  True,  True, False, False, False, False, False],
         [ True,  True,  True,  True,  True,  True, False, False, False, False],
         [ True,  True,  True,  True,  True,  True, False, False, False, False],
         [ True,  True,  True,  True,  True,  True, False, False, False, False],
         [ True,  True,  True,  True,  True,  True, False, False, False, False],
         [ True,  True,  True,  True,  True,  True, False, False, False, False]]])


In [111]:
final_mask = (sequence == -1) | torch.triu(torch.ones((1, 10, 10)), diagonal=1).type(torch.bool)
print(final_mask)

tensor([[[False,  True,  True,  True,  True,  True,  True,  True,  True,  True],
         [False, False,  True,  True,  True,  True,  True,  True,  True,  True],
         [False, False, False,  True,  True,  True,  True,  True,  True,  True],
         [False, False, False, False,  True,  True,  True,  True,  True,  True],
         [False, False, False, False, False,  True,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True]]])


In [112]:
final_mask = (sequence == -1).unsqueeze(0).unsqueeze(0) | torch.triu(torch.ones((1, 10, 10)), diagonal=1).type(torch.bool)
print(final_mask)

tensor([[[False,  True,  True,  True,  True,  True,  True,  True,  True,  True],
         [False, False,  True,  True,  True,  True,  True,  True,  True,  True],
         [False, False, False,  True,  True,  True,  True,  True,  True,  True],
         [False, False, False, False,  True,  True,  True,  True,  True,  True],
         [False, False, False, False, False,  True,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True],
         [False, False, False, False, False, False,  True,  True,  True,  True]]])


In [131]:
from Translator.dataset import get_translation_dataset

ds = get_translation_dataset("de", "en", "16")
#create_tokenizer(ds,"de")
#create_tokenizer(ds,"en")

In [132]:
ds

DatasetDict({
    train: Dataset({
        features: ['translation'],
        num_rows: 4548885
    })
    validation: Dataset({
        features: ['translation'],
        num_rows: 2169
    })
    test: Dataset({
        features: ['translation'],
        num_rows: 2999
    })
})

In [158]:
max_de_length = 0
max_de_idx = 0
max_en_length = 0
max_en_idx = 0
for i in range(len(ds["train"])):
    if len(ds["train"][i]["translation"]["de"]) > max_de_length: 
        max_de_length = len(ds["train"][i]["translation"]["de"])
        max_de_idx = i
    if len(ds["train"][i]["translation"]["en"]) > max_en_length:
        max_en_length = len(ds["train"][i]["translation"]["en"])
        max_en_idx = i

In [159]:
len(ds["train"][i]["translation"]["de"])

245

In [160]:
print(max_de_length, max_en_length)
print(max_de_idx, max_en_idx)

2769 2296
15847 15847


In [162]:
ds["train"][15847]["translation"]["de"]

"Was man von dieser dreifachen politischen, natürlichen und poetischen Erklärung des Brandes des Justizpalastes im Jahre 1618 auch denken mag, die unglücklicherweise feststehende Thatsache ist der Brand. Heute ist nur noch sehr wenig vorhanden, Dank diesem Unglücke, Dank vornehmlich den verschiedenen Wiederherstellungsversuchen im Laufe der Zeit, welche vollends zu Grunde gerichtet haben, was er verschont hatte; es ist nur noch sehr wenig von diesem ersten Aufenthaltsorte der französischen Könige, von diesem ursprünglichen Palastbaue des Louvre übrig, der schon zu Philipps des Schönen Zeit so alt war, daß man hier nach den Spuren der prächtigen Bauten forschte, die vom König Robert aufgeführt und von Helgaldus beschrieben worden sind. Fast alles ist verschwunden. Was ist aus dem Zimmer der Kanzlei geworden, wo der heilige Ludwig »seine Ehe vollzog«? Was aus dem Garten, wo er Recht sprach, »angethan mit einem Camelotrocke, mit einem grobwollenen Obergewande ohne Aermel, und mit einem Ma

In [154]:
from datasets import load_dataset   
ds = load_dataset("opus_books", "de-en")

In [155]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'translation'],
        num_rows: 51467
    })
})

In [172]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'translation'],
        num_rows: 51467
    })
})

In [175]:
filtered_dataset = ds.filter(lambda x: len(x['translation']["de"]) <= 256).filter(lambda x: len(x['translation']["en"]) <= 256)

Filter: 100%|██████████| 45271/45271 [00:00<00:00, 118699.32 examples/s]


In [176]:
filtered_dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'translation'],
        num_rows: 45009
    })
})

In [2]:
print("Notice: Its recommended to train on GPU using Cuda "
      "when working with large models. Consider using CUDA "
      "if available for your GPU.")

Notice: Its recommended to train on GPU using Cuda when working with large models. Consider using CUDA if available for your GPU.


In [3]:
print(f"current epoch: \n")

current epoch: 



In [4]:
from tqdm import tqdm

In [7]:
for _ in range(2):
    print("start")
    for i in tqdm(range(1000)):
        pass

start


100%|██████████| 1000/1000 [00:00<?, ?it/s]


start


100%|██████████| 1000/1000 [00:00<?, ?it/s]


In [9]:
from datasets import load_dataset
ds = load_dataset("opus_books", "de-en")

C:\Users\Home\PycharmProjects\ModProgProject\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
ds["train"].train_test_split(test_size=0.1)

DatasetDict({
    train: Dataset({
        features: ['id', 'translation'],
        num_rows: 46320
    })
    test: Dataset({
        features: ['id', 'translation'],
        num_rows: 5147
    })
})

In [13]:
import torch

In [14]:
decoder_sequence = torch.empty(256).fill_(3)

In [16]:
decoder_sequence.shape

torch.Size([256])

In [22]:
s = decoder_sequence.view(1,256)

In [25]:
s[0,3]= 7

In [26]:
s

tensor([[7., 3., 3., 7., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3.,

In [29]:
from Translator.dataset import load_tokenizer_from_save
tokenizer = load_tokenizer_from_save("de")

In [41]:
prediction = torch.Tensor(tokenizer.encode("Das Haus ist rot.").ids).int()
prediction

tensor([  89,  433,   29, 1912,    5], dtype=torch.int32)

In [36]:
tokenizer.encode(".").ids[0]

5

In [43]:
tokenizer.decode(prediction.tolist())

'Das Haus ist rot .'

In [44]:
a = torch.Tensor([[1,2,3]])

In [45]:
a.tolist()

[[1.0, 2.0, 3.0]]

In [53]:
torch.argmax(torch.tensor([1,0,2,3],dtype=torch.int), dim=-1)

tensor(3)

In [49]:
A[0]

IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

In [57]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
torch.tensor(3).view(1)

tensor([3])

In [62]:
[epoch+1 for epoch in range(3)]

[1, 2, 3]

In [63]:
str(23)

'23'

In [9]:
from datasets import load_dataset, get_dataset_config_names

In [7]:
get_dataset_config_names('opus_books')

['ca-de',
 'ca-en',
 'ca-hu',
 'ca-nl',
 'de-en',
 'de-eo',
 'de-es',
 'de-fr',
 'de-hu',
 'de-it',
 'de-nl',
 'de-pt',
 'de-ru',
 'el-en',
 'el-es',
 'el-fr',
 'el-hu',
 'en-eo',
 'en-es',
 'en-fi',
 'en-fr',
 'en-hu',
 'en-it',
 'en-nl',
 'en-no',
 'en-pl',
 'en-pt',
 'en-ru',
 'en-sv',
 'eo-es',
 'eo-fr',
 'eo-hu',
 'eo-it',
 'eo-pt',
 'es-fi',
 'es-fr',
 'es-hu',
 'es-it',
 'es-nl',
 'es-no',
 'es-pt',
 'es-ru',
 'fi-fr',
 'fi-hu',
 'fi-no',
 'fi-pl',
 'fr-hu',
 'fr-it',
 'fr-nl',
 'fr-no',
 'fr-pl',
 'fr-pt',
 'fr-ru',
 'fr-sv',
 'hu-it',
 'hu-nl',
 'hu-no',
 'hu-pl',
 'hu-pt',
 'hu-ru',
 'it-nl',
 'it-pt',
 'it-ru',
 'it-sv']

In [11]:
ds = load_dataset("opus_books", "de-pt")

Generating train split: 100%|██████████| 1102/1102 [00:00<00:00, 68216.17 examples/s]


In [12]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'translation'],
        num_rows: 1102
    })
})

In [14]:
ds["train"]["translation"]

[{'de': 'Translation: Antonie Zimmermann', 'pt': 'Source: Wikisource'},
 {'de': 'Alice’s Abenteuer im Wunderland',
  'pt': 'Alice no País das Maravilhas'},
 {'de': 'Lewis Carroll', 'pt': 'Lewis Carroll'},
 {'de': 'Erstes Kapitel – Hinunter in den Kaninchenbau.',
  'pt': 'Capítulo I Descendo a Toca do Coelho'},
 {'de': 'Alice fing an sich zu langweilen; sie saß schon lange bei ihrer Schwester am Ufer und hatte nichts zu tun. Das Buch, das ihre Schwester las, gefiel ihr nicht; denn es waren weder Bilder noch Gespräche darin. »Und was nützen Bücher,« dachte Alice, »ohne Bilder und Gespräche ?«',
  'pt': 'Alice estava começando a ficar muito cansada de sentar-se ao lado de sua irmã no banco e de não ter nada para fazer: uma ou duas vezes havia espiado o livro que a irmã estava lendo, mas não havia imagens nem diálogos nele, "e para que serve um livro", pensou Alice, "sem imagens nem diálogos?"'},
 {'de': 'Sie überlegte sich eben, (so gut es ging, denn sie war schläfrig und dumm von der Hit

In [16]:
a,b="de-en".split("-")

In [17]:
a

'de'

In [18]:
b

'en'

In [19]:
b = set()

In [21]:
b.add("de")

In [22]:
b.add("en")

In [23]:
b

{'de', 'en'}

In [24]:
b.add("de")

In [25]:
b

{'de', 'en'}

In [29]:
for i in ds["train"]["translation"]:
    print(i)
    break

{'de': 'Translation: Antonie Zimmermann', 'pt': 'Source: Wikisource'}


In [30]:
ds

DatasetDict({
    train: Dataset({
        features: ['id', 'translation'],
        num_rows: 1102
    })
})

In [34]:
type(ds["train"][4])

dict

In [36]:
print(ds["train"])

Dataset({
    features: ['id', 'translation'],
    num_rows: 1102
})


In [39]:
import re

def string_length_and_character_filter(input_string):
    # Remove allowed punctuation and spaces from the input string
    cleaned_input = re.sub(r"[ \!\',;:¡¿\-\.?]", '', input_string)
    
    # Check if the remaining characters are all alphabetic and if the original string has a valid length
    if 8 <= len(input_string) <= 256 and cleaned_input.isalpha():
        return True
    else:
        return False

# Examples
print(string_length_and_character_filter("Hello, world!"))     # Output: True
print(string_length_and_character_filter("What's up!"))        # Output: True
print(string_length_and_character_filter("Hello_world"))       # Output: False
print(string_length_and_character_filter("¡Hola, mundo!"))     # Output: True
print(string_length_and_character_filter("Héllö, Wörld!"))     # Output: True
print(string_length_and_character_filter("Hello@world"))       # Output: False
print(string_length_and_character_filter("Well, why not?"))    # Output: True
print(string_length_and_character_filter("Look: a test."))     # Output: True
print(string_length_and_character_filter("Is this correct?"))  # Output: True


True
True
False
True
True
False
True
True
True


In [1]:
from LanguageDetector.dataset import LanguageDetector

In [2]:
ld_ds = LanguageDetector(8, 256, 1000)

filter ca-de


100%|██████████| 4445/4445 [00:00<00:00, 147717.18it/s]


filter ca-en


100%|██████████| 4605/4605 [00:00<00:00, 192249.89it/s]


filter ca-hu


100%|██████████| 4463/4463 [00:00<00:00, 178488.68it/s]


filter ca-nl


100%|██████████| 4329/4329 [00:00<00:00, 164492.20it/s]


filter de-en


100%|██████████| 51467/51467 [00:00<00:00, 153541.57it/s]


filter de-eo


100%|██████████| 1363/1363 [00:00<00:00, 136034.18it/s]


filter de-es


100%|██████████| 27526/27526 [00:00<00:00, 54852.48it/s]


filter de-fr


100%|██████████| 34916/34916 [00:00<00:00, 146520.99it/s]


filter de-hu


100%|██████████| 51780/51780 [00:00<00:00, 153420.66it/s]


filter de-it


100%|██████████| 27381/27381 [00:00<00:00, 134930.38it/s]


filter de-nl


100%|██████████| 15622/15622 [00:00<00:00, 177111.86it/s]


filter de-pt


100%|██████████| 1102/1102 [00:00<00:00, 140738.17it/s]


filter de-ru


100%|██████████| 17373/17373 [00:00<00:00, 146935.46it/s]


filter el-en


100%|██████████| 1285/1285 [00:00<00:00, 128337.95it/s]


filter el-es


100%|██████████| 1096/1096 [00:00<00:00, 109295.23it/s]


filter el-fr


100%|██████████| 1237/1237 [00:00<00:00, 112035.28it/s]


filter el-hu


100%|██████████| 1090/1090 [00:00<00:00, 103725.19it/s]


filter en-eo


100%|██████████| 1562/1562 [00:00<00:00, 145195.31it/s]


filter en-es


100%|██████████| 93470/93470 [00:00<00:00, 142277.78it/s]


filter en-fi


100%|██████████| 3645/3645 [00:00<00:00, 195792.20it/s]


filter en-fr


100%|██████████| 127085/127085 [00:00<00:00, 148039.55it/s]


filter en-hu


100%|██████████| 137151/137151 [00:00<00:00, 157966.67it/s]


filter en-it


100%|██████████| 32332/32332 [00:00<00:00, 136636.93it/s]


filter en-nl


100%|██████████| 38652/38652 [00:00<00:00, 153856.02it/s]


filter en-no


100%|██████████| 3499/3499 [00:00<00:00, 166366.67it/s]


filter en-pl


100%|██████████| 2831/2831 [00:00<00:00, 171412.33it/s]


filter en-pt


100%|██████████| 1404/1404 [00:00<00:00, 155792.56it/s]


filter en-ru


100%|██████████| 17496/17496 [00:00<00:00, 165426.16it/s]


filter en-sv


100%|██████████| 3095/3095 [00:00<00:00, 140111.94it/s]


filter eo-es


100%|██████████| 1677/1677 [00:00<00:00, 145195.44it/s]


filter eo-fr


100%|██████████| 1588/1588 [00:00<00:00, 139199.46it/s]


filter eo-hu


100%|██████████| 1636/1636 [00:00<00:00, 163405.36it/s]


filter eo-it


100%|██████████| 1453/1453 [00:00<00:00, 145085.67it/s]


filter eo-pt


100%|██████████| 1259/1259 [00:00<00:00, 155945.57it/s]


filter es-fi


100%|██████████| 3344/3344 [00:00<00:00, 180404.81it/s]


filter es-fr


100%|██████████| 56319/56319 [00:00<00:00, 143720.15it/s]


filter es-hu


100%|██████████| 78800/78800 [00:00<00:00, 156027.86it/s]


filter es-it


100%|██████████| 28868/28868 [00:00<00:00, 137685.96it/s]


filter es-nl


100%|██████████| 32247/32247 [00:00<00:00, 138410.87it/s]


filter es-no


100%|██████████| 3585/3585 [00:00<00:00, 177684.84it/s]


filter es-pt


100%|██████████| 1327/1327 [00:00<00:00, 144653.73it/s]


filter es-ru


100%|██████████| 16793/16793 [00:00<00:00, 151655.32it/s]


filter fi-fr


100%|██████████| 3537/3537 [00:00<00:00, 172354.64it/s]


filter fi-hu


100%|██████████| 3504/3504 [00:00<00:00, 184249.44it/s]


filter fi-no


100%|██████████| 3414/3414 [00:00<00:00, 184703.89it/s]


filter fi-pl


100%|██████████| 2814/2814 [00:00<00:00, 175558.11it/s]


filter fr-hu


100%|██████████| 89337/89337 [00:00<00:00, 152096.22it/s]


filter fr-it


100%|██████████| 14692/14692 [00:00<00:00, 120170.51it/s]


filter fr-nl


100%|██████████| 40017/40017 [00:00<00:00, 148559.67it/s]


filter fr-no


100%|██████████| 3449/3449 [00:00<00:00, 172281.76it/s]


filter fr-pl


100%|██████████| 2825/2825 [00:00<00:00, 165951.10it/s]


filter fr-pt


100%|██████████| 1263/1263 [00:00<00:00, 139913.53it/s]


filter fr-ru


100%|██████████| 8197/8197 [00:00<00:00, 162867.65it/s]


filter fr-sv


100%|██████████| 3002/3002 [00:00<00:00, 133072.30it/s]


filter hu-it


100%|██████████| 30949/30949 [00:00<00:00, 145660.59it/s]


filter hu-nl


100%|██████████| 43428/43428 [00:00<00:00, 160824.86it/s]


filter hu-no


100%|██████████| 3410/3410 [00:00<00:00, 178396.43it/s]


filter hu-pl


100%|██████████| 2859/2859 [00:00<00:00, 172880.57it/s]


filter hu-pt


100%|██████████| 1184/1184 [00:00<00:00, 147737.73it/s]


filter hu-ru


100%|██████████| 26127/26127 [00:00<00:00, 161260.75it/s]


filter it-nl


100%|██████████| 2359/2359 [00:00<00:00, 75995.32it/s]


filter it-pt


100%|██████████| 1163/1163 [00:00<00:00, 127229.41it/s]


filter it-ru


100%|██████████| 17906/17906 [00:00<00:00, 163545.87it/s]


filter it-sv


100%|██████████| 2998/2998 [00:00<00:00, 138348.81it/s]


In [3]:
len(ld_ds.data)

16000

In [28]:
ld_ds.data

['Egli non dice mai una cosa non vera.',
 'Non era forse lo stesso?',
 'Diana e Maria giungeranno in settimana e vorrei che trovassero tutto in ordine.',
 'Ed ecco, bevi.',
 'Aleksej aveva detto allora al fratello che questa somma gli sarebbe stata sufficiente fino al giorno in cui non si sarebbe ammogliato, il che probabilmente non si sarebbe verificato mai.',
 'Sedette allo scrittoio e, invece di scrivere, incrociò le braccia sul tavolo, poggiò la testa su di esse e pianse, così come piangono i bambini, singhiozzando e scotendo il petto.',
 'Ma se Dio vuole, le erbe son buone.',
 'Mi collocai allora nel vano di una finestra, sedendomi sui piedi come i turchi, e tirando la tenda di damasco rosso, mi trovai rinchiusa in un doppio ritiro.',
 'Ho visto Stiva quando era innamorato di te.',
 'Queste due gioie, la caccia fortunata e il biglietto della moglie, erano tanto grandi che i due piccoli dispiaceri, seguìti alla caccia, passarono con facilità per Levin.',
 'Questo fuoco sottile mi h

In [8]:
"test1".isalpha()

False

In [18]:
3"Ο κύριος βαρώνος ήταν ένας από τους".isalpha()

False

In [19]:
"the house".isalpha()

False

In [16]:
for e in "Ο κύριος βαρώνος ήταν ένας από τους":
    if not e.isalpha():
        print(e)

In [13]:
import re

def tokenize(seq):
    # Define patterns
    stc = r"[!,;:¡¿.?]"  # Special token characters
    word = r"\b\w+(?:[-']\w+)*\b"  # Match words with internal connectors
    connector = r"[-']"  # Standalone connector (if not part of a word)
    
    # Use regex to capture all valid tokens
    pattern = f"({stc})|({word})|({connector})"
    tokens = [match.group() for match in re.finditer(pattern, seq)]
    
    return tokens

# Example usage:
seq = "Hello, world! I'm Cedric-how are you?"
tokens = tokenize(seq)
print(tokens)


['Hello', ',', 'world', '!', "I'm", 'Cedric-how', 'are', 'you', '?']


In [14]:
d = {"a": 3, "b": 0, "c": "test"}

In [18]:
"test" in d

False

In [22]:
t = "t"
res = d[t] if t in d else 0
res

0

In [23]:
S = set()

In [24]:
S.add("a")
S.add("b")
S.add("c")

In [25]:
S

{'a', 'b', 'c'}

In [26]:
S[0]

TypeError: 'set' object is not subscriptable

In [1]:
from LanguageDetector.dataset import LanguageDetector

In [2]:
LD = LanguageDetector.build_from_iterator(8, 256, 5000, 2, "LD/test")


filter de-en


100%|██████████| 51467/51467 [00:00<00:00, 139082.03it/s]


In [8]:
T = LD.word_tokenizer.encode("Das Haus ist rot.")
list(T)

[tensor(97), tensor(262), tensor(73), tensor(662), tensor(3)]

In [9]:
" ".join(LD.word_tokenizer.tokens[idx] for idx in T.tolist())

'das haus ist rot .'

In [4]:
LD.word_tokenizer.tokenize(LD.data[123]['sequence'])

[{'token': 'nun', 'id': 149},
 {'token': 'schwiegen', 'id': 2237},
 {'token': 'beide', 'id': 239},
 {'token': 'lange', 'id': 236},
 {'token': '.', 'id': 6}]

In [17]:
LD.word_tokenizer.tokenize("Das Haus ist rot.".lower())

[{'token': 'das', 'id': 45},
 {'token': 'haus', 'id': 223},
 {'token': 'ist', 'id': 61},
 {'token': 'rot', 'id': 843},
 {'token': '.', 'id': 6}]

In [18]:
[entry['id'] for entry in LD.word_tokenizer.tokenize("Das Haus ist rot.".lower()) ]

[45, 223, 61, 843, 6]

In [16]:
LD.data[12]

{'sequence': 'je früher, desto besser.', 'language': 'de'}

In [8]:
len(LD.word_tokenizer.ids)

9787

In [9]:
len(LD.language_tokenizer)

2

In [15]:
LD.language_tokenizer[LD.data[12]['language']]

0

'de'

In [16]:
A = {'sequence': 'und jetzt begann das eintönige zirpen einer grille, das keine menschliche macht zum schweigen zu bringen vermag.', 'language': 'de'}

In [19]:
A["language"]

de
