In [110]:
import random

import torch
import torch.nn as nn
import modules
import math
import random

In [29]:
def printt(t:torch.Tensor):
    print(t, t.shape)

In [84]:
bs = 4
sl = 10
sl2 = 5
input_vocab_size = 20
d = 6
h = 2

In [70]:
inp_emb = modules.Embedding(input_vocab_size, d)
pos_emb = modules.Embedding(sl, d)

In [71]:
# batches of random sequences described by ids
seq = torch.randint(0, input_vocab_size, (bs,sl))
printt(seq)

tensor([[18, 17,  7, 13, 18, 12, 13, 15, 19, 18],
        [14, 18, 10,  5,  8, 16,  1, 19, 18, 15],
        [17,  5, 13, 16,  0,  1,  3,  2,  7, 11],
        [ 5,  7, 14,  9, 11, 14,  7, 12, 16,  2]]) torch.Size([4, 10])


In [72]:
seq_emb = inp_emb(seq)
printt(seq_emb)

tensor([[[ 0.7774, -0.2962, -6.0705, -0.1232,  0.9104,  3.2231],
         [-3.2247,  0.7750, -4.0129,  3.1585,  0.7181,  1.9608],
         [ 2.3310, -1.2658,  2.2745, -1.4404, -0.5730,  1.8327],
         [ 3.2067,  0.2134,  2.2233,  0.8664,  0.0252, -1.1584],
         [ 0.7774, -0.2962, -6.0705, -0.1232,  0.9104,  3.2231],
         [ 1.7432, -2.8732, -2.5260,  3.6703,  3.6140,  1.2436],
         [ 3.2067,  0.2134,  2.2233,  0.8664,  0.0252, -1.1584],
         [ 0.8599, -1.4885,  0.9750,  1.8406, -1.4321, -3.1658],
         [ 1.1429,  1.0125,  0.4125, -1.0598,  2.5379, -1.0979],
         [ 0.7774, -0.2962, -6.0705, -0.1232,  0.9104,  3.2231]],

        [[ 1.7982,  1.0486,  1.0344, -2.9477, -1.1388,  3.1828],
         [ 0.7774, -0.2962, -6.0705, -0.1232,  0.9104,  3.2231],
         [-2.5442, -3.7065, -1.5641, -1.8306,  2.1405,  2.0041],
         [-5.3023, -0.1889,  2.2303,  3.1703,  0.1476,  1.9541],
         [-0.8814,  2.8125,  0.4263,  5.1661, -5.5426, -1.1200],
         [-4.6212, -0.7

In [73]:
pos = torch.arange(sl)
printt(pos)
printt(pos.unsqueeze(0))
printt(pos.unsqueeze(0).expand(bs,-1))
pos_reshaped = pos.unsqueeze(0).expand(bs,-1)
seq_full_emb = seq_emb + pos_emb(pos_reshaped)
printt(seq_full_emb)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([4, 10])
tensor([[[ -3.2136,   1.3501,  -5.4501,   1.6192,   1.6856,   2.5150],
         [ -2.6953,  -1.6941,  -8.6048,   0.6619,  -0.6075,  -0.4119],
         [  4.0161,  -0.4916,   3.8141,   0.0716,   3.6729,  -0.3350],
         [  2.3216,  -3.0725,  -1.0888,   2.9225,   1.8451,  -1.5247],
         [  1.8645,   2.2592,  -5.5353,   0.5149,  -0.2535,   5.4112],
         [  2.3163,  -1.0390,  -3.5176,   6.0337,   3.7962,   2.1442],
         [  3.7075,   1.4104,   2.6856,  -0.0930,  -2.8852,  -2.8191],
         [ -1.3609,  -0.5267,   3.7631,   0.7644,   0.3904,  -2.4377],
         [ -2.0340,  -0.4800,   0.4828,  -0.7030,  -0.2978,  -3.3756],
         [  2.1380,  -1.4931,  -5.9917,   3.4685,  -1.9315,   6

In [74]:
# self attention:
w = nn.init.uniform_(torch.empty(d, d), -1/math.sqrt(d), 1/math.sqrt(d))
printt(w)

tensor([[ 0.0154,  0.4012, -0.3616, -0.1253, -0.2010,  0.1004],
        [ 0.1760, -0.3195,  0.3684, -0.2179, -0.1073, -0.3081],
        [ 0.3479,  0.2822, -0.1547,  0.0496,  0.0656,  0.2159],
        [-0.1147, -0.2796,  0.0242, -0.2654,  0.1928,  0.0959],
        [ 0.2524, -0.1068,  0.2732,  0.2392, -0.3270, -0.0525],
        [-0.2776,  0.0111,  0.1299, -0.3600, -0.0772,  0.0349]]) torch.Size([6, 6])


In [75]:
w @ seq_full_emb

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [4, 6] but got: [4, 10].

In [76]:
w = torch.randint(0,10, (d, d))
x = torch.randint(0,10, (bs,1,d))
b = torch.randint(0,10, (d,1))
printt(w)
printt(x)
printt(b)

tensor([[9, 2, 3, 3, 0, 5],
        [4, 2, 6, 1, 3, 8],
        [1, 9, 1, 9, 1, 3],
        [8, 9, 7, 7, 0, 1],
        [5, 5, 8, 5, 5, 8],
        [2, 8, 0, 7, 9, 0]]) torch.Size([6, 6])
tensor([[[7, 1, 3, 5, 5, 6]],

        [[8, 0, 7, 2, 7, 4]],

        [[0, 2, 1, 4, 0, 3]],

        [[3, 8, 7, 0, 7, 8]]]) torch.Size([4, 1, 6])
tensor([[4],
        [6],
        [0],
        [9],
        [7],
        [2]]) torch.Size([6, 1])


In [77]:
torch.matmul(w,x.transpose(1,2))

tensor([[[119],
         [116],
         [ 87],
         [127],
         [162],
         [102]],

        [[119],
         [129],
         [ 52],
         [131],
         [173],
         [ 93]],

        [[ 34],
         [ 38],
         [ 64],
         [ 56],
         [ 62],
         [ 44]],

        [[104],
         [155],
         [113],
         [153],
         [210],
         [133]]])

In [78]:
torch.matmul(w,x.transpose(1,2)) + b

tensor([[[123],
         [122],
         [ 87],
         [136],
         [169],
         [104]],

        [[123],
         [135],
         [ 52],
         [140],
         [180],
         [ 95]],

        [[ 38],
         [ 44],
         [ 64],
         [ 65],
         [ 69],
         [ 46]],

        [[108],
         [161],
         [113],
         [162],
         [217],
         [135]]])

In [130]:
# now in sdp_attention: 
q = torch.randint(0,10, (bs, h, sl2, d//h))
k = torch.randint(0,10, (bs, h, sl2, d//h))
v = torch.randint(0,10, (bs, h, sl2, d//h))


In [131]:
printt(q[1,1])
printt(k[1,1])
qk_prod = q @ k.transpose(-1,-2)
printt(q[1,1] @ k[1,1].transpose(-1,-2))
printt(qk_prod[1,1])
print(qk_prod.shape)

tensor([[6, 7, 5],
        [9, 2, 3],
        [9, 0, 6],
        [2, 5, 6],
        [5, 2, 0]]) torch.Size([5, 3])
tensor([[1, 2, 1],
        [5, 2, 4],
        [5, 5, 0],
        [9, 4, 1],
        [3, 7, 5]]) torch.Size([5, 3])
tensor([[25, 64, 65, 87, 92],
        [16, 61, 55, 92, 56],
        [15, 69, 45, 87, 57],
        [18, 44, 35, 44, 71],
        [ 9, 29, 35, 53, 29]]) torch.Size([5, 5])
tensor([[25, 64, 65, 87, 92],
        [16, 61, 55, 92, 56],
        [15, 69, 45, 87, 57],
        [18, 44, 35, 44, 71],
        [ 9, 29, 35, 53, 29]]) torch.Size([5, 5])
torch.Size([4, 2, 5, 5])


In [132]:
score = (q @ k.transpose(-1,-2)) / math.sqrt(d//h)

In [184]:
def rand_mask(bs, sl):
    b = torch.zeros(bs, 1, sl)
    for i in range(bs):
        pad_start = random.randint(0,sl)
        b[i,0,0:pad_start] = 1
    return b

In [185]:
def causal_mask(bs,sl):
    b = torch.ones(bs, sl, sl)
    for i in range(bs):
        b[i] = torch.tril(torch.ones((sl, sl)))
    print(b.shape)
    return b

In [190]:
#mask=rand_mask(bs, sl2).type(torch.bool).unsqueeze(1)
mask=causal_mask(bs,sl2).type(torch.bool).unsqueeze(1)
printt(mask)

print(mask[0,0,1,4])

torch.Size([4, 5, 5])
tensor([[[[ True, False, False, False, False],
          [ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True,  True, False],
          [ True,  True,  True,  True,  True]]],


        [[[ True, False, False, False, False],
          [ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True,  True, False],
          [ True,  True,  True,  True,  True]]],


        [[[ True, False, False, False, False],
          [ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True,  True, False],
          [ True,  True,  True,  True,  True]]],


        [[[ True, False, False, False, False],
          [ True,  True, False, False, False],
          [ True,  True,  True, False, False],
          [ True,  True,  True,  True, False],
          [ True,  True,  True,  True,  True]]]]) torch.Size([4, 1, 5, 5]

In [183]:
#print(score)
print(score.masked_fill(~mask, float("-inf")))

tensor([[[[ 20.7846,   0.0000,  16.1658,   9.2376,   0.0000],
          [ 36.3731,   1.7321,  29.4449,  13.8564,  15.5885],
          [ 60.6218,   3.4641,  59.4671,  30.0222,  24.2487],
          [ 26.5581,   1.1547,  23.0940,  11.5470,   9.2376],
          [ 28.2902,   3.4641,  25.9808,   9.2376,  30.0222]],

         [[ 68.1273, 101.6136,  38.1051,  87.1799,  73.3235],
          [ 46.7654,  69.2820,  15.5885,  55.4256,  53.6936],
          [ 66.9726, 101.6136,  38.1051,  92.3760,  69.2820],
          [ 62.3538,  92.3760,  36.9504,  77.9423,  67.5500],
          [ 30.5996,  46.1880,  18.4752,  41.5692,  31.7543]]],


        [[[ 34.0637,   6.3509,  18.4752,  10.3923,  25.4034],
          [ 35.7957,  20.2073,  39.2598,  58.3124,   8.0829],
          [ 44.4560,   8.0829,  16.7432,   4.6188,  37.5278],
          [ 10.9697,   3.4641,   9.8150,  10.3923,   5.1962],
          [ 51.9615,  27.7128,  39.8372,  61.7765,  22.5167]],

         [[ 14.4338,  36.9504,  37.5278,  50.2295,  53.1162],


In [126]:
# logical and test:
A = torch.randint(0,2,(1,4))
B = torch.randint(0,2,(1,4,4))
C = A & B
printt(A)
printt(B)
printt(C)

tensor([[0, 0, 1, 1]]) torch.Size([1, 4])
tensor([[[0, 0, 0, 1],
         [0, 1, 1, 0],
         [0, 1, 1, 1],
         [0, 0, 0, 1]]]) torch.Size([1, 4, 4])
tensor([[[0, 0, 0, 1],
         [0, 0, 1, 0],
         [0, 0, 1, 1],
         [0, 0, 0, 1]]]) torch.Size([1, 4, 4])


In [192]:
torch.zeros(4,1,dtype=torch.long).shape

torch.Size([4, 1])

In [194]:
lf = nn.CrossEntropyLoss()
lf(torch.tensor([[2.3e-04, 9.9e-01]]), torch.tensor([0]))

tensor(1.3058)

In [195]:
pred = torch.tensor([[2.3470e-05, 9.9998e-01],
        [4.2851e-05, 9.9996e-01],
        [8.1603e-05, 9.9992e-01],
        [2.6992e-06, 1.0000e+00],
        [2.4531e-05, 9.9998e-01],
        [3.8442e-05, 9.9996e-01],
        [1.1708e-04, 9.9988e-01],
        [3.5274e-05, 9.9996e-01]])

In [196]:
lang = torch.tensor([0, 0, 0, 0, 0, 0, 0, 0])

In [197]:
lf(pred,lang)

tensor(1.3132)